repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        types: [python]
        entry: make -s isort
        pass_filenames: false
      - id: black
        name: black
        language: system
        types: [python]
        entry: make -s black
        pass_filenames: false