services:
    db:
        restart: always
        image: "postgres:16.3"
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
        command: -p ${POSTGRES_PORT}
        networks:
            - prod-net
        volumes:
            - ./.db:/var/lib/postgresql/data
    backend:
        restart: always
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
        volumes:
            - ./.logs:/app/.logs/
        command: ./docker-entrypoint.sh
        networks:
            - prod-net
        environment:
            DEV: 0
    nginx:
        restart: always
        image: nginx:1.27.0-alpine
        ports:
            - ${PORT:-80}:80
        volumes:
            - ./nginx/nginx-proxy-prod.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
          - backend
        networks:
            - prod-net

networks:
    prod-net: