services:
    db:
        restart: always
        image: "postgres:16.3"
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
        command: -p ${POSTGRES_PORT}
        networks:
            - dev-net
        volumes:
            - ./.db_dev:/var/lib/postgresql/data
    backend:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
        env_file:
            - .env
        volumes:
            - ./backend:/app/backend
            - ./migrations:/app/migrations
            - ./alembic.ini:/app/alembic.ini
            - ./.logs:/app/.logs/
        command: ./docker-entrypoint.sh
        networks:
            - dev-net
        ports:
            - 8080:8000
        environment:
            DEV: 1
networks:
    dev-net: