version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./backend:/backend
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
        networks:
            - dev-net

    nginx:
        image: nginx:1.21.6-alpine
        ports:
            - 8080:80
        volumes:
            - ./nginx/nginx-proxy-dev.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
          - backend
        networks:
            - dev-net

networks:
    dev-net: