version: '3'
services:
    db:
        restart: always
        image: "postgres:14.2"
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
        command: -p ${POSTGRES_PORT}
        networks:
            - dev-net
    backend:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        volumes:
            - ./backend:/app/backend
        command: uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000
        networks:
            - dev-net

    nginx:
        restart: always
        image: nginx:1.21.6-alpine
        ports:
            - 8080:80
        volumes:
            - ./nginx/nginx-proxy-dev.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
          - backend
        networks:
            - dev-net

networks:
    dev-net: