version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: uvicorn main:app --host 0.0.0.0 --port 8000
        networks:
            - prod-net

    nginx:
        image: nginx:1.21.6-alpine
        ports:
            - ${PORT:-80}:80
        volumes:
            - ./nginx/nginx-proxy-prod.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
          - backend
        networks:
            - prod-net

networks:
    prod-net: