"""Add BuildingsLog model

Revision ID: cef6f13620e6
Revises: 
Create Date: 2022-05-24 22:17:27.521099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef6f13620e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.create_table(
        'buildings_logs',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('rq_recv_dt', sa.DateTime(timezone=True), nullable=False),
        sa.Column('rq_duration_ms', sa.Integer(), nullable=False),
        sa.Column(
            'data_source',
            sa.Enum('BDOT', 'EGIB', name='buildingsdatasource'),
            nullable=False
        ),
        sa.Column('lat', sa.Float(), nullable=False),
        sa.Column('lon', sa.Float(), nullable=False),
        sa.Column('building_count', sa.Integer(), nullable=True),
        sa.CheckConstraint('building_count is null or building_count >= 0'),
        sa.CheckConstraint('rq_duration_ms >= 0'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    # WARNING cannot auto drop type buildingsdatasource (enum)
    op.drop_table('buildings_logs')
    # ### end Alembic commands ###
