name: Checks (build, tests, quality)

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          sudo apt install -y libgdal-dev
          make install
      - name: Quality check – format
        if: success() || failure()
        run: |
          make format-check
      - name: Quality check – lint
        if: success() || failure()
        run: |
          make lint-check